# Generated by Django 5.2.4 on 2025-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="profile/default.jpg", upload_to="profile"),
        ),
    ]
