# Generated by Django 5.2.4 on 2025-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="background.jpg", upload_to="blog"),
        ),
    ]
